language: generic 
sudo : required

services:
  -docker

before_install:
  - docker build -t bernardss/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bernardss/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-736019120020"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: $aws_access_key
  secret_access_key: 
    secure: "$secret_access_key"
